(set-language-environment 'Chinese-GB)
(setq locale-coding-system 'euc-cn)
(set-default-coding-systems 'euc-cn)
(set-clipboard-coding-system 'euc-cn)
(set-selection-coding-system 'euc-cn)
(setenv "HOME" (getenv "UserProfile"))
(provide 'init-nt)
